name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '❗️ Breaking Changes'
    labels:
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
exclude-labels:
  - 'chore'
autolabeler:
  - label: 'chore'
    branch:
      - '/^chore\/.+/'
      - '/^docs\/.+/'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/^feature\/.+/'
      - '/^feat\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES